apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rxg8kullv-nodejs 
  janus-idp.io/tekton: rxg8kullv-nodejs
  backstage.io/kubernetes-id: rxg8kullv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rxg8kullv-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  