apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rxg8kullv-nodejs
  janus-idp.io/tekton: rxg8kullv-nodejs
  backstage.io/kubernetes-id: rxg8kullv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rxg8kullv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
